import { useState, type ComponentType } from "react";
import { Bell, CalendarDays, Check, ChevronDown, CircleHelp, Clock3, Code2, Download, Eye, Flag, FolderKanban, Globe2, Headphones, LayoutDashboard, Link2, Menu, MessageCircle, MoreHorizontal, PackageCheck, Plus, Search, Settings2, ShieldCheck, Sparkles, UserRound, WalletCards, X } from "lucide-react";
import { Link } from "wouter";

export const dashboardSections = [
  ["WORKSPACE", [[LayoutDashboard, "Dashboard"], [FolderKanban, "My project"], [Eye, "Preview website"], [MessageCircle, "Revisions"], [WalletCards, "Payments"], [Download, "Downloads"]]],
  ["BUSINESS", [[UserRound, "Customers"], [PackageCheck, "Products"], [CalendarDays, "Bookings"], [Globe2, "Domain"]]],
  ["CARE", [[Settings2, "Technical care"], [ShieldCheck, "System health"], [Headphones, "Support"]]],
] as const;

export const dashboardMilestones = ["Brief received", "Scope confirmed", "In build", "Preview ready", "Approved", "Delivery"];
export const dashboardTasks = [["Design direction", "Complete", true], ["Frontend build", "Complete", true], ["Business copy", "In progress", false], ["Content handover", "In progress", false], ["Final quality check", "Next", false]] as const;
const activities: Array<{ Icon: ComponentType<{ size?: number }>; title: string; text: string; time: string }> = [
  { Icon: Eye, title: "Preview available", text: "A workspace version is ready to review.", time: "Now" },
  { Icon: MessageCircle, title: "Revision route ready", text: "Your feedback path is open.", time: "Today" },
  { Icon: Code2, title: "Build updated", text: "Layout and responsive work progressed.", time: "Yesterday" },
  { Icon: PackageCheck, title: "Project opened", text: "Your FerixBuilder workspace was created.", time: "Earlier" },
];

export default function Dashboard() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [period, setPeriod] = useState("This week");
  const [notice, setNotice] = useState<string | null>(null);
  const act = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(null), 2800); };
  const sideContent = <>{dashboardSections.map(([title, items]) => <div className="dash-nav-group" key={title}><p>{title}</p>{items.map(([Icon, label]) => <button key={label} className={label === "Dashboard" ? "active" : ""} onClick={() => act(`${label} is available in this preview dashboard.`)}><Icon size={16} /><span>{label}</span>{label === "Revisions" && <b>2</b>}</button>)}</div>)}</>;
  return <div className="dashboard-shell">
    <aside className={mobileOpen ? "dash-sidebar mobile-open" : "dash-sidebar"}><div className="dash-brand"><span><Sparkles size={15} /></span><b>Ferix</b>Builder<button onClick={() => setMobileOpen(false)}><X size={18} /></button></div>{sideContent}<div className="dash-profile"><div className="profile-avatar">FB</div><div><b>FerixBuilder demo</b><span>Preview account</span></div><ChevronDown size={14} /></div></aside>
    <main className="dash-main"><header className="dash-header"><button className="dash-menu" onClick={() => setMobileOpen(true)}><Menu size={20} /></button><div className="dash-search"><Search size={17} /><input placeholder="Search your workspace..." /><kbd>⌘ K</kbd></div><div className="dash-header-actions"><button onClick={() => act("You have 2 preview notifications.")}><Bell size={18} /><i>2</i></button><button onClick={() => act("Your latest project update is ready.")}><MessageCircle size={18} /><i>1</i></button><Link href="/" className="dash-return">Back to site</Link></div></header>
      <section className="dash-welcome"><div><p className="dash-kicker">CUSTOMER WORKSPACE / PREVIEW MODE</p><h1>Welcome back, <em>FerixBuilder</em> <span>✦</span></h1><p>Here is the latest view of your project and delivery route.</p></div><button className="dash-primary" onClick={() => act("A new project request is ready to start.")}><Plus size={18} /> New request</button></section>
      <section className="dash-stat-grid"><Stat icon={<FolderKanban />} label="Project status" value="In build" note="75% complete" color="purple" /><Stat icon={<MessageCircle />} label="Revision route" value="2" note="Changes included" color="mint" /><Stat icon={<Eye />} label="Private preview" value="Ready" note="Available to review" color="blue" /><Stat icon={<WalletCards />} label="Project value" value="Tailored" note="Confirmed after approval" color="orange" /><Stat icon={<Download />} label="Delivery files" value="Prepared" note="Available after approval" color="violet" /></section>
      <section className="dash-content-grid"><div className="dash-left-col"><article className="dash-card project-map"><div className="card-title"><div><span className="icon-box purple"><FolderKanban size={18} /></span><div><h2>Project overview</h2><p>FerixBuilder platform · Customer workspace</p></div></div><button onClick={() => act("Project details view opened in preview.")}>View project details</button></div><div className="milestones">{dashboardMilestones.map((step, index) => <div key={step} className={index < 4 ? "done" : index === 4 ? "current" : ""}><i>{index < 4 ? <Check size={13} /> : index + 1}</i><b>{step}</b><small>{index === 0 ? "Today" : index === 3 ? "Ready now" : ""}</small></div>)}</div></article>
        <div className="dash-two-col"><article className="dash-card preview-card"><div className="card-title"><div><span className="icon-box purple"><Eye size={18} /></span><div><h2>Website preview</h2><p>Your workspace preview is ready.</p></div></div></div><div className="preview-window"><div><span /><span /><span /><b>FERIXBUILDER</b></div><section><p>YOUR WORKSPACE.<br /><strong>CLEARER BY DESIGN.</strong></p><button>Explore</button><aside><i /><i /><i /></aside></section></div><div className="preview-actions"><button onClick={() => act("Preview is opening in this demonstration.")}><Eye size={15} /> Open preview</button><button onClick={() => act("Preview share link copied for this demonstration.")}><Link2 size={15} /> Share preview</button></div></article>
          <article className="dash-card progress-card"><div className="card-title"><div><span className="icon-box blue"><Sparkles size={18} /></span><div><h2>Project progress</h2><p>Momentum across the week.</p></div></div><select value={period} onChange={(event) => setPeriod(event.target.value)}><option>This week</option><option>This month</option></select></div><div className="chart"><div className="chart-y"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><svg viewBox="0 0 440 170" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#7045f6" stopOpacity=".25"/><stop offset="1" stopColor="#7045f6" stopOpacity="0"/></linearGradient></defs><path d="M0 145 L65 123 L130 105 L195 91 L260 83 L325 61 L390 48 L440 30 L440 170 L0 170Z" fill="url(#area)"/><path d="M0 145 L65 123 L130 105 L195 91 L260 83 L325 61 L390 48 L440 30" fill="none" stroke="#7045f6" strokeWidth="3"/><g fill="#7045f6">{[[0,145],[65,123],[130,105],[195,91],[260,83],[325,61],[390,48],[440,30]].map(([cx,cy]) => <circle key={`${cx}-${cy}`} cx={cx} cy={cy} r="4"/>)}</g></svg><div className="chart-days"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div><div className="task-list">{dashboardTasks.map(([task, status, complete]) => <div key={task}><i className={complete ? "complete" : "working"}>{complete ? <Check size={12} /> : <Clock3 size={12} />}</i><span>{task}</span><b className={complete ? "complete-text" : "working-text"}>{status}</b></div>)}</div></article></div></div>
        <aside className="dash-right-col"><article className="dash-card status-card"><div className="card-title"><div><span className="icon-box purple"><Flag size={18} /></span><div><h2>Project status</h2><p>Current stage</p></div></div></div><strong className="status-pill">Preview ready</strong><p>Your workspace version has been shaped for review. You can explore it, collect feedback, and request changes before approval.</p><button className="review-button" onClick={() => act("Private preview opened in this dashboard demonstration.")}><Eye size={16} /> Review website</button><button className="outline-button" onClick={() => act("Revision request panel opened in this demonstration.")}><MessageCircle size={16} /> Request changes</button><button className="approval-button" onClick={() => act("Approval route previewed. Payment is not enabled in this demonstration.")}><Check size={16} /> Approve & continue</button></article>
          <article className="dash-card activity-card"><div className="card-title"><div><span className="icon-box blue"><Clock3 size={18} /></span><div><h2>Recent activity</h2></div></div><button onClick={() => act("All activity is visible in this preview.")}>View all</button></div>{activities.map(({ Icon, title, text, time }, index) => <div className="activity" key={title}><span className={`activity-icon a${index}`}><Icon size={14} /></span><div><b>{title}</b><p>{text}</p><small>{time}</small></div></div>)}</article></aside>
      </section>
      <section className="dash-footer-grid"><article className="dash-card help-card"><span className="icon-box purple"><CircleHelp size={18} /></span><div><h2>Need help?</h2><p>The project support route is ready whenever you need context or next steps.</p></div><button className="dash-primary small" onClick={() => act("Support ticket preview opened.")}>Open support</button></article><article className="dash-card useful-card"><span className="icon-box blue"><Link2 size={18} /></span><div><h2>Useful links</h2><Link href="/how-it-works">How it works <Arrow /></Link><Link href="/pricing">Project scope <Arrow /></Link><Link href="/examples">Examples <Arrow /></Link></div></article><article className="dash-card manager-card"><div className="manager-avatar">FB</div><div><h2>Project team</h2><p>FerixBuilder will guide your project through the agreed delivery route.</p><button onClick={() => act("Message area preview opened.")}><MessageCircle size={14} /> Message team</button></div></article><article className="dash-card updates-card"><Bell size={22} /><div><h2>Stay updated</h2><p>Receive important workspace updates as your project progresses.</p><button onClick={() => act("Workspace notifications enabled in preview.")}>Enable updates <Bell size={14} /></button></div></article></section>
    </main>{notice && <div className="dash-notice"><Check size={15} /> {notice}</div>}</div>;
}

function Stat({ icon, label, value, note, color }: { icon: React.ReactNode; label: string; value: string; note: string; color: string }) { return <article className="dash-stat"><span className={`stat-icon ${color}`}>{icon}</span><div><p>{label}</p><h2>{value}</h2><small>{note}</small>{label === "Project status" && <i className="stat-progress"><b /></i>}</div></article>; }
function Arrow() { return <MoreHorizontal size={15} />; }
