import { useEffect, useRef, useState } from "react";
import {
  BellRing, Building2, Check, CircleCheckBig, CloudUpload, CreditCard, Download, FileText, FolderOpen,
  Laptop, MessageCircle, Monitor, PackagePlus, Paperclip, Save, Send, Settings2, ShieldCheck,
  Smartphone, Tablet, UploadCloud, UserPlus, UsersRound,
} from "lucide-react";
import { completePreviewOnboarding, getOnboardingDraft, getPreviewAccount, saveOnboardingDraft, type OnboardingDraft } from "@/lib/customerAccess";

type FeatureSurfaceProps = { page: string; notify: (message: string) => void; navigate: (path: string) => void; heroAction?: "support" | "settings"; heroActionVersion?: number };

const modules: Record<string, { label: string; description: string; icon: typeof UsersRound; filterLabel: string; statuses: readonly string[]; detail: string }> = {
  customers: { label: "customer", description: "Customers connected to the business application will appear here.", icon: UsersRound, filterLabel: "Active only", statuses: ["Prospect", "Active"], detail: "Contact profile and workspace relationship" },
  products: { label: "product", description: "Products or service offers made available in the delivered application will appear here.", icon: PackagePlus, filterLabel: "Ready only", statuses: ["Draft", "Ready"], detail: "Offer details and website placement" },
  bookings: { label: "booking type", description: "Booking types and availability settings will appear here when this module is included.", icon: Settings2, filterLabel: "Open only", statuses: ["Draft", "Open"], detail: "Availability and booking configuration" },
};

type PreviewRecord = { name: string; status: string; detail: string };
type SupportTicket = { id: number; message: string };

export default function FeatureSurface({ page, notify, navigate, heroAction, heroActionVersion = 0 }: FeatureSurfaceProps) {
  const [step, setStep] = useState(0);
  const [onboardingDraft, setOnboardingDraft] = useState<OnboardingDraft>(() => getOnboardingDraft());
  const account = getPreviewAccount();
  const [draftSaved, setDraftSaved] = useState(false);
  const [previewMode, setPreviewMode] = useState("Desktop");
  const [revision, setRevision] = useState("");
  const [revisionSent, setRevisionSent] = useState(false);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [ticket, setTicket] = useState("");
  const [messages, setMessages] = useState<SupportTicket[]>([]);
  const [services, setServices] = useState<string[]>([]);
  const [managementSubmitted, setManagementSubmitted] = useState(false);
  const [businessRecords, setBusinessRecords] = useState<Record<string, PreviewRecord[]>>({ customers: [], products: [], bookings: [] });
  const [recordSearch, setRecordSearch] = useState("");
  const [filterActive, setFilterActive] = useState(false);
  const [openRecord, setOpenRecord] = useState<PreviewRecord | null>(null);
  const [quoteReviewOpen, setQuoteReviewOpen] = useState(false);
  const [paymentRouteOpen, setPaymentRouteOpen] = useState(false);
  const [guideOpen, setGuideOpen] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [prefs, setPrefs] = useState({ project: true, support: true, product: false });
  const [settingsSaved, setSettingsSaved] = useState(false);
  const [approvalOpen, setApprovalOpen] = useState(false);
  const [previewApproved, setPreviewApproved] = useState(false);
  const [managementNeeds, setManagementNeeds] = useState("");
  const [businessExported, setBusinessExported] = useState(false);
  const [memberEmail, setMemberEmail] = useState("");
  const [members, setMembers] = useState<string[]>([]);
  const ticketInput = useRef<HTMLTextAreaElement>(null);
  const settingsForm = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (modules[page]) {
      setRecordSearch("");
      setFilterActive(false);
      setOpenRecord(null);
    }
  }, [page]);

  useEffect(() => {
    if (!heroActionVersion) return;
    if (heroAction === "support") {
      ticketInput.current?.scrollIntoView({ behavior: "smooth", block: "center" });
      window.setTimeout(() => ticketInput.current?.focus(), 180);
    }
    if (heroAction === "settings") {
      setSettingsSaved(true);
      settingsForm.current?.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }, [heroAction, heroActionVersion]);

  if (page === "onboarding") {
    const stages = ["Business", "Contact", "Build", "Content", "Brand", "Inspiration", "Requirements", "Hosting", "Review"];
    const updateDraft = <K extends keyof OnboardingDraft>(key: K, value: OnboardingDraft[K]) => setOnboardingDraft((current) => ({ ...current, [key]: value }));
    const saveDraft = () => { saveOnboardingDraft(onboardingDraft); setDraftSaved(true); };
    const continueOnboarding = () => { saveDraft(); if (step < stages.length - 1) setStep(step + 1); };
    const submitRequest = () => { if (!onboardingDraft.businessName.trim() || !onboardingDraft.projectType || !onboardingDraft.requirements.trim()) return notify("Please add your business name, what you want built, and your main requirements before submitting."); saveDraft(); completePreviewOnboarding(); navigate("/dashboard"); };
    const projectTypes = [["Business website", "Present your business professionally online."], ["Online store", "Sell products and accept orders online."], ["Restaurant website", "Menus, reservations, and restaurant information."], ["Service website", "Showcase services and receive enquiries."], ["Booking website", "Let customers schedule appointments."], ["Custom application", "Describe a more advanced business need."]];
    const brandStyles = ["Modern", "Minimal", "Luxury", "Bold", "Professional", "Creative", "Elegant", "Corporate"];
    const stepContent = [
      <div className="onboard-fields" key="business"><label>Business name<input value={onboardingDraft.businessName} onChange={(event) => updateDraft("businessName", event.target.value)} placeholder="ABC Fashion" /></label><label>Business category<select value={onboardingDraft.category} onChange={(event) => updateDraft("category", event.target.value)}><option value="">Choose a category</option>{["Fashion", "Restaurant", "Electronics", "Beauty & Cosmetics", "Construction", "Real Estate", "Education", "Professional Services", "Health & Wellness", "E-commerce", "Other"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="full">Short description<textarea value={onboardingDraft.description} onChange={(event) => updateDraft("description", event.target.value)} placeholder="Tell us what your business does." /></label></div>,
      <div className="onboard-fields" key="contact"><label>Business phone<input value={onboardingDraft.businessPhone} onChange={(event) => updateDraft("businessPhone", event.target.value)} placeholder="+234 000 000 0000" /></label><label>WhatsApp<input value={onboardingDraft.whatsapp} onChange={(event) => updateDraft("whatsapp", event.target.value)} placeholder="+234 000 000 0000" /></label><label>Business email<input type="email" value={onboardingDraft.businessEmail} onChange={(event) => updateDraft("businessEmail", event.target.value)} placeholder="business@example.com" /></label><label>Business address<input value={onboardingDraft.address} onChange={(event) => updateDraft("address", event.target.value)} placeholder="Street address" /></label><label>City<input value={onboardingDraft.city} onChange={(event) => updateDraft("city", event.target.value)} placeholder="Your city" /></label><label>State or region<input value={onboardingDraft.state} onChange={(event) => updateDraft("state", event.target.value)} placeholder="Your state" /></label><label>Country<input value={onboardingDraft.country} onChange={(event) => updateDraft("country", event.target.value)} placeholder="Your country" /></label><label>Opening hours<input value={onboardingDraft.openingHours} onChange={(event) => updateDraft("openingHours", event.target.value)} placeholder="Mon–Sat, 9am–6pm" /></label><p className="form-subheading full">Optional social profiles</p><label>Instagram<input value={onboardingDraft.instagram} onChange={(event) => updateDraft("instagram", event.target.value)} placeholder="instagram.com/yourbusiness" /></label><label>Facebook<input value={onboardingDraft.facebook} onChange={(event) => updateDraft("facebook", event.target.value)} placeholder="facebook.com/yourbusiness" /></label><label>TikTok<input value={onboardingDraft.tiktok} onChange={(event) => updateDraft("tiktok", event.target.value)} placeholder="tiktok.com/@yourbusiness" /></label><label>X<input value={onboardingDraft.xProfile} onChange={(event) => updateDraft("xProfile", event.target.value)} placeholder="x.com/yourbusiness" /></label><label className="full">YouTube<input value={onboardingDraft.youtube} onChange={(event) => updateDraft("youtube", event.target.value)} placeholder="youtube.com/@yourbusiness" /></label></div>,
      <div className="choice-grid" key="build">{projectTypes.map(([title, detail]) => <button type="button" key={title} className={onboardingDraft.projectType === title ? "choice selected" : "choice"} onClick={() => updateDraft("projectType", title)}><b>{title}</b><span>{detail}</span>{onboardingDraft.projectType === title && <Check size={15} />}</button>)}</div>,
      <div className="onboard-fields" key="content"><label className="full">{onboardingDraft.projectType === "Online store" ? "Products, categories, and availability" : onboardingDraft.projectType === "Booking website" ? "Services, availability, and booking questions" : "Content you can provide"}<textarea value={onboardingDraft.contentNote} onChange={(event) => updateDraft("contentNote", event.target.value)} placeholder={onboardingDraft.projectType === "Online store" ? "Share products, prices, categories, or availability. You can also provide products later." : onboardingDraft.projectType === "Booking website" ? "Share services, timings, availability, or booking questions. You can also provide details later." : "Tell us about products, services, menus, staff, or other material you can provide. You can also provide this later."} /></label><div className="provide-later">{onboardingDraft.projectType === "Online store" ? "You can provide products later. The project request will record that an online store is needed." : "You do not need to provide all business content now. You can upload or add it later through Project Files."}</div></div>,
      <div className="onboard-fields" key="brand"><label className="full">Preferred brand style<div className="style-chips">{brandStyles.map((style) => <button type="button" key={style} className={onboardingDraft.brandStyle === style ? "selected" : ""} onClick={() => updateDraft("brandStyle", style)}>{style}</button>)}</div></label><div className="brand-source full"><button type="button" className={onboardingDraft.brandSource === "colours" ? "selected" : ""} onClick={() => updateDraft("brandSource", "colours")}>Choose brand colours</button><button type="button" className={onboardingDraft.brandSource === "guide" ? "selected" : ""} onClick={() => updateDraft("brandSource", "guide")}>Upload brand guide</button></div>{onboardingDraft.brandSource === "colours" && <label className="full">Brand colours<input value={onboardingDraft.brandColours} onChange={(event) => updateDraft("brandColours", event.target.value)} placeholder="For example: #6F42C1, navy, cream" /></label>}{onboardingDraft.brandSource === "guide" && <label className="full file-drop compact-upload"><input type="file" onChange={(event) => setSelectedFile(event.target.files?.[0]?.name ?? null)} /><UploadCloud size={20} /><b>{selectedFile ? `${selectedFile} brand guide staged` : "Stage your brand guide"}</b><span>Files stay local to this preview; the production flow uses private project storage.</span></label>}<label className="full file-drop compact-upload"><input type="file" onChange={(event) => setSelectedFile(event.target.files?.[0]?.name ?? null)} /><UploadCloud size={20} /><b>{selectedFile ? `${selectedFile} staged` : "Stage a logo, business photos, or product images"}</b><span>Files stay local to this preview; the production flow uses private project storage.</span></label></div>,
      <div className="onboard-fields" key="inspiration"><label className="full">Website you like<input value={onboardingDraft.inspirationUrl} onChange={(event) => updateDraft("inspirationUrl", event.target.value)} placeholder="https://example.com" /></label><label className="full">What do you like about it?<textarea value={onboardingDraft.inspirationNote} onChange={(event) => updateDraft("inspirationNote", event.target.value)} placeholder="For example: the homepage structure, colours, or product layout." /></label><label className="full file-drop compact-upload"><input type="file" onChange={(event) => setSelectedFile(event.target.files?.[0]?.name ?? null)} /><UploadCloud size={20} /><b>{selectedFile ? `${selectedFile} staged as inspiration` : "Stage an inspiration screenshot"}</b><span>Use a website link, screenshots, or both to give the project team visual context.</span></label></div>,
      <div className="onboard-fields" key="requirements"><label className="full">Tell us exactly what you want<textarea value={onboardingDraft.requirements} onChange={(event) => updateDraft("requirements", event.target.value)} placeholder="Do not worry about technical terms. Describe what you want your website or application to do." /></label><button type="button" className="quiet attach-action" onClick={() => { saveDraft(); navigate("/workspace/files"); }}><Paperclip size={15} /> Add project files</button></div>,
      <div className="choice-grid two-choice" key="hosting"><button type="button" className={onboardingDraft.managementPreference === "self" ? "choice selected" : "choice"} onClick={() => updateDraft("managementPreference", "self")}><b>I’ll manage it myself</b><span>We deliver your approved website or source materials for your own hosting route.</span></button><button type="button" className={onboardingDraft.managementPreference === "managed" ? "choice selected" : "choice"} onClick={() => updateDraft("managementPreference", "managed")}><b>Manage it for me</b><span>Request optional hosting, maintenance, and technical management. FerixBuilder reviews this before activation.</span></button></div>,
      <div className="request-review" key="review"><div><span>Business</span><b>{onboardingDraft.businessName || "Not added"}</b></div><div><span>Type</span><b>{onboardingDraft.projectType || "Not selected"}</b></div><div><span>Description</span><b>{onboardingDraft.description || "Not added"}</b></div><div><span>Contact</span><b>{onboardingDraft.businessEmail || onboardingDraft.businessPhone || "Not added"}</b></div><div><span>Requirements</span><b>{onboardingDraft.requirements || "Not added"}</b></div><div><span>Hosting</span><b>{onboardingDraft.managementPreference === "managed" ? "Management requested for review" : onboardingDraft.managementPreference === "self" ? "Self-managed delivery" : "Not selected"}</b></div></div>,
    ][step];
    return <section className="workflow-surface onboarding-surface"><div className="workflow-card"><div className="workflow-heading"><div><p>PROJECT REQUEST ONBOARDING</p><h2>{step === 8 ? "Review your project request." : `Tell us about your ${stages[step].toLowerCase()}.`}</h2><span>Account creation is complete. This guided setup collects business and project details separately, and every step can be saved.</span></div><b>Step {step + 1} / 9</b></div><div className="onboarding-steps expanded">{stages.map((stage, index) => <button type="button" key={stage} className={index === step ? "active" : index < step ? "done" : ""} onClick={() => setStep(index)}><i>{index < step ? <Check size={13} /> : index + 1}</i><span>{stage}</span></button>)}</div><div className="workflow-form onboarding-form">{stepContent}<div className="form-actions"><button type="button" className="quiet" onClick={saveDraft}><Save size={15} /> Save and continue later</button>{step > 0 && <button type="button" className="quiet" onClick={() => setStep(step - 1)}>Back</button>}<button type="button" className="dash-primary" onClick={step === 8 ? submitRequest : continueOnboarding}>{step === 8 ? "Submit project request" : "Continue"}</button></div>{draftSaved && <div className="request-card"><b>Onboarding progress saved</b><span>Your account setup stays separate from this draft. You can continue this local preview draft whenever you return.</span></div>}</div></div></section>;
  }

  if (page === "project") {
    return <section className="workflow-surface"><div className="workflow-grid"><div className="workflow-card"><div className="workflow-heading"><div><p>PROJECT SCOPE AND QUOTE</p><h2>Everything agreed, in one place.</h2><span>Track scope, included work, milestones, and the point at which a quote is ready for your decision.</span></div><FileText size={24} /></div><div className="scope-list"><div><b>Core delivery</b><span>Public website, private customer workspace, responsive layouts</span><i>Included</i></div><div><b>Review allowance</b><span>Two structured revision rounds after the private preview</span><i>Included</i></div><div><b>Handover route</b><span>Protected delivery material released after approval and payment verification</span><i>Controlled</i></div></div><div className="form-actions"><button className="quiet" onClick={() => navigate("/workspace/files")}>Review project files</button><button className="dash-primary" onClick={() => setQuoteReviewOpen(true)}>Review quote decision</button></div>{quoteReviewOpen && <div className="request-card"><b>Quote decision pending</b><span>An authorised FerixBuilder scope and price must be issued before this project can be accepted or paid for.</span></div>}</div><aside className="workflow-card"><p className="mini-label">MILESTONE HISTORY</p><ol className="workflow-list"><li><b>01</b><span>Brief received</span></li><li><b>02</b><span>Scope confirmation in progress</span></li><li><b>03</b><span>Build begins after acceptance</span></li><li><b>04</b><span>Private preview before payment</span></li></ol><div className="empty-state">No financial amount is displayed until an authorised scope and quote are created.</div></aside></div></section>;
  }

  if (page === "files") {
    return <section className="workflow-surface"><div className="workflow-card"><div className="workflow-heading"><div><p>PROJECT FILES</p><h2>Keep project material together.</h2><span>Upload brand assets, requirements, screenshots, and reference material securely.</span></div><FolderOpen size={24} /></div><label className="file-drop"><input type="file" onChange={(event) => setSelectedFile(event.target.files?.[0]?.name ?? null)} /><UploadCloud size={24} /><b>Choose a file to stage in preview</b><span>Images, documents, screenshots, and audio references are supported in the full project flow.</span></label>{selectedFile ? <div className="staged-file"><FileText size={19} /><div><b>{selectedFile}</b><span>Staged locally for this preview session</span></div><button onClick={() => { setSelectedFile(null); notify("Staged file removed."); }}>Remove</button></div> : <div className="empty-state">No project files have been added in this preview. Your real project files will stay private and access-controlled.</div>}</div></section>;
  }

  if (page === "preview") {
    const viewOptions = [[Monitor, "Desktop"], [Tablet, "Tablet"], [Smartphone, "Mobile"]] as const;
    return <section className="workflow-surface preview-surface"><div className="workflow-card"><div className="workflow-heading"><div><p>PRIVATE WEBSITE PREVIEW</p><h2>Review the work on every screen.</h2><span>Preview version 01 is ready. Leave feedback before you approve the project.</span></div><div className="view-switch">{viewOptions.map(([Icon, label]) => <button key={label} className={previewMode === label ? "active" : ""} onClick={() => setPreviewMode(label)}><Icon size={15} /> {label}</button>)}</div></div><div className={`private-preview ${previewMode.toLowerCase()}`}><div className="private-browser"><span /><span /><span /><b>ferixbuilder preview</b></div><div className="private-site"><p>YOUR BUSINESS<br /><strong>MADE CLEARER.</strong></p><button>Explore</button></div></div><div className="form-actions"><button className="quiet" onClick={() => setShareOpen((current) => !current)}>{shareOpen ? "Hide share details" : "Share private preview"}</button><button className="quiet" onClick={() => navigate("/workspace/revisions")}>Request changes</button><button className="dash-primary" onClick={() => setApprovalOpen(true)}>Approve direction</button></div>{shareOpen && <div className="request-card"><b>Private preview sharing</b><span>When sharing is authorised, this area provides the review audience, expiry period, and access restrictions for the preview link.</span></div>}{approvalOpen && !previewApproved && <div className="approval-card"><div><b>Approve preview version 01?</b><span>Confirming this tells FerixBuilder that the reviewed direction is ready for the controlled quote and payment stage. It does not charge you.</span></div><div><button className="quiet" onClick={() => setApprovalOpen(false)}>Not yet</button><button className="dash-primary" onClick={() => { setPreviewApproved(true); setApprovalOpen(false); }}>Confirm approval</button></div></div>}{previewApproved && <div className="request-card"><b>Preview direction approved</b><span>Your decision has been recorded in this preview. Continue to the Delivery journey to review the quote and payment route.</span><button className="quiet inline-action" onClick={() => navigate("/workspace/delivery")}>Open delivery</button></div>}</div></section>;
  }

  if (page === "revisions") {
    return <section className="workflow-surface"><div className="workflow-grid"><div className="workflow-card"><div className="workflow-heading"><div><p>REVISION WORKSPACE</p><h2>Feedback with clear context.</h2><span>You have 2 included revision rounds. Additional work is reviewed before it is added.</span></div><b>2 left</b></div><div className="revision-status"><CircleCheckBig size={18} /><span>Preview is ready for your feedback.</span></div><label>What would you like to change?<textarea value={revision} onChange={(event) => setRevision(event.target.value)} placeholder="Describe the screen, content, or interaction you want changed." /></label><div className="form-actions"><button className="quiet" onClick={() => navigate("/workspace/files")}><Paperclip size={15} /> Attach from project files</button><button className="dash-primary" onClick={() => { if (!revision.trim()) return notify("Add feedback before creating a revision request."); setRevisionSent(true); setRevision(""); notify("Revision request created in preview mode."); }}>Create request</button></div>{revisionSent && <div className="request-card"><b>Revision request #01</b><span>Submitted for team review · remaining allowance: 1</span></div>}</div><aside className="workflow-card"><p className="mini-label">HOW REVISIONS WORK</p><ol className="workflow-list"><li><b>01</b><span>Describe the change and attach context.</span></li><li><b>02</b><span>The team reviews entitlement and impact.</span></li><li><b>03</b><span>The updated preview returns for review.</span></li></ol></aside></div></section>;
  }

  if (page === "payments") {
    return <section className="workflow-surface"><div className="workflow-grid"><div className="workflow-card"><div className="workflow-heading"><div><p>QUOTE AND PAYMENT</p><h2>Approval comes before payment.</h2><span>Your exact scope, price, and payment request will appear here after the project review.</span></div><CreditCard size={24} /></div><div className="quote-rows"><div><span>Project quote</span><b>Awaiting scope confirmation</b></div><div><span>Payment state</span><b>Not due</b></div><div><span>Invoice history</span><b>No invoice released</b></div></div><button className="dash-primary wide" onClick={() => setPaymentRouteOpen(true)}>View payment route</button>{paymentRouteOpen && <div className="request-card"><b>Payment route protected</b><span>After final approval, a server-verified payment request and invoice appear here. Delivery remains locked until a separate quality release is completed.</span></div>}</div><aside className="workflow-card"><p className="mini-label">CONTROLLED DELIVERY</p><p className="side-copy">Approval creates the payment request. Payment verification alone never releases customer downloads; final delivery is separately checked and released.</p><div className="status-stack"><span><Check size={14} /> Review preview</span><span>02 Approve scope</span><span>03 Payment request</span><span>04 Verified delivery</span></div></aside></div></section>;
  }

  if (page === "downloads") {
    return <section className="workflow-surface"><div className="workflow-card"><div className="workflow-heading"><div><p>DELIVERY CENTRE</p><h2>Released files will be protected.</h2><span>Delivery material becomes available after approval, verified payment, and final release.</span></div><ShieldCheck size={24} /></div><div className="delivery-lock"><Download size={26} /><div><b>Delivery is not released yet</b><span>Your project remains in its preview stage. Nothing is missing; protected downloads simply unlock later in the delivery lifecycle.</span></div></div><div className="delivery-checklist"><span><Check size={14} /> Approved project version</span><span>02 Verified payment</span><span>03 Final delivery quality check</span><span>04 Protected release</span></div><button className="quiet" onClick={() => setGuideOpen((current) => !current)}>{guideOpen ? "Hide delivery guide" : "View delivery guide"}</button>{guideOpen && <div className="request-card"><b>Delivery guide</b><span>When release is authorised, this page will show delivery contents, expiry-limited access, deployment instructions, and the exact version released.</span></div>}</div></section>;
  }

  if (page === "management") {
    const options = ["Hosting and deployment", "Domain management", "Technical maintenance", "Monitoring and backups"];
    const toggle = (service: string) => setServices((current) => current.includes(service) ? current.filter((item) => item !== service) : [...current, service]);
    return <section className="workflow-surface"><div className="workflow-grid"><div className="workflow-card"><div className="workflow-heading"><div><p>MANAGED SERVICE REQUEST</p><h2>Ask FerixBuilder to keep things running.</h2><span>Management stays optional. A request is reviewed before any service is accepted.</span></div><ShieldCheck size={24} /></div><div className="service-options">{options.map((option) => <button key={option} className={services.includes(option) ? "selected" : ""} onClick={() => toggle(option)}><i>{services.includes(option) ? <Check size={14} /> : "+"}</i><span>{option}</span></button>)}</div><label>Tell us about your operating needs<textarea value={managementNeeds} onChange={(event) => setManagementNeeds(event.target.value)} placeholder="Traffic expectations, launch date, existing domain, or support needs." /></label><button className="dash-primary wide" onClick={() => services.length ? setManagementSubmitted(true) : notify("Choose at least one requested service.")}>Request management review</button>{managementSubmitted && <div className="request-card"><b>Management request submitted</b><span>{services.join(", ")} selected. {managementNeeds.trim() ? `Operating note: ${managementNeeds}` : "No operating note added."} Your request is pending FerixBuilder review before any managed operations are enabled.</span></div>}</div><aside className="workflow-card"><p className="mini-label">MANAGEMENT STATUS</p><h3>{managementSubmitted ? "Under review" : "Not requested"}</h3><p className="side-copy">Only accepted customers see managed-service summaries for hosting, domain, health, deployments, and backups.</p></aside></div></section>;
  }

  if (page === "support") {
    return <section className="workflow-surface"><div className="workflow-grid"><div className="workflow-card conversation-card"><div className="workflow-heading"><div><p>SUPPORT TICKETS</p><h2>Project help, with the right context.</h2><span>Open a ticket and keep the delivery conversation in one place.</span></div><BellRing size={23} /></div><div className="conversation-log">{messages.length ? messages.map((message) => <div key={message.id} className="customer-message"><b>Ticket #{String(message.id).padStart(2, "0")} · You</b><span>{message.message}</span></div>) : <div className="empty-state">No open support tickets in preview mode. Your first message creates a numbered project request.</div>}</div><div className="message-composer"><textarea ref={ticketInput} value={ticket} onChange={(event) => setTicket(event.target.value)} placeholder="Describe what you need help with..." /><button onClick={() => { if (!ticket.trim()) return notify("Write a support message first."); setMessages((current) => [...current, { id: current.length + 1, message: ticket }]); setTicket(""); notify("Support ticket created in preview mode."); }}><Send size={16} /></button></div></div><aside className="workflow-card"><p className="mini-label">SUPPORT ROUTE</p><div className="status-stack"><span><Check size={14} /> Project context attached</span><span>Priority follows your agreement</span><span>Attachments stay private</span></div></aside></div></section>;
  }

  if (page === "settings") {
    return <section className="workflow-surface"><div className="workflow-grid"><div className="workflow-card"><div className="workflow-heading"><div><p>ACCOUNT SETTINGS</p><h2>Your profile and workspace preferences.</h2><span>Manage preferences and customer-space notifications in one place.</span></div><Settings2 size={24} /></div><div ref={settingsForm} className="workflow-form compact"><label>Display name<input defaultValue={account?.fullName || "FerixBuilder customer"} /></label><label>Business role<input defaultValue="Business owner" /></label><label className="full">Workspace email<input defaultValue={account?.email || "customer@example.com"} /></label></div><button className="dash-primary" onClick={() => setSettingsSaved(true)}>Save settings</button>{settingsSaved && <div className="request-card"><b>Preferences saved in preview</b><span>Your profile and notification selections are retained locally for this preview session.</span></div>}</div><aside className="workflow-card"><p className="mini-label">NOTIFICATIONS</p>{([['project', 'Project updates'], ['support', 'Support replies'], ['product', 'New business activity']] as const).map(([key, label]) => <button className="pref-row" key={key} onClick={() => setPrefs((current) => ({ ...current, [key]: !current[key] }))}><span>{label}</span><i className={prefs[key] ? "on" : ""}>{prefs[key] ? "On" : "Off"}</i></button>)}<div className="member-panel"><p className="mini-label">BUSINESS MEMBERS</p><div><input value={memberEmail} onChange={(event) => setMemberEmail(event.target.value)} placeholder="member@business.com" /><button onClick={() => { if (!memberEmail.trim()) return notify("Add a business member email first."); setMembers((current) => [...current, memberEmail.trim()]); setMemberEmail(""); }}>Add</button></div>{members.map((member) => <span key={member}>{member} <b>Pending invitation</b></span>)}</div></aside></div></section>;
  }

  if (modules[page]) {
    const module = modules[page]; const ModuleIcon = module.icon;
    const records = businessRecords[page] ?? [];
    const searchResults = records.filter((record) => record.name.toLowerCase().includes(recordSearch.toLowerCase()));
    const filteredRecords = filterActive ? searchResults.filter((record) => record.status === module.statuses[1]) : searchResults;
    return <section className="workflow-surface"><div className="workflow-card"><div className="workflow-heading"><div><p>BUSINESS DATA MODULE</p><h2>Manage your {module.label} records.</h2><span>{module.description}</span></div><ModuleIcon size={24} /></div><div className="module-toolbar"><input value={recordSearch} onChange={(event) => setRecordSearch(event.target.value)} placeholder={`Search ${module.label}s`} /><button className={filterActive ? "quiet active-filter" : "quiet"} onClick={() => setFilterActive((current) => !current)}>{filterActive ? "Show all" : module.filterLabel}</button><button className="quiet" onClick={() => setBusinessExported(true)}>Export view</button><button className="dash-primary" onClick={() => { const index = records.length; const next = { name: `New ${module.label} ${index + 1}`, status: module.statuses[index % module.statuses.length], detail: module.detail }; setBusinessRecords((current) => ({ ...current, [page]: [...(current[page] ?? []), next] })); setOpenRecord(next); notify(`${next.name} added.`); }}><UserPlus size={15} /> Add {module.label}</button></div>{records.length ? filteredRecords.length ? <div className="record-list">{filteredRecords.map((record) => <div className="record-row" key={record.name}><ModuleIcon size={19} /><div><b>{record.name}</b><span>{record.status} · {record.detail}</span></div><button onClick={() => setOpenRecord(record)}>Open</button></div>)}</div> : <div className="empty-state">No {module.label} records match this view. Add another record or choose Show all.</div> : <div className="empty-state">No {module.label} records yet. Add one to test this delivered business-data module.</div>}{businessExported && <div className="request-card"><b>Protected export prepared in preview</b><span>The production flow creates a tenant-scoped, time-limited data export. No other customer’s records are included.</span></div>}{openRecord && <div className="request-card"><b>{openRecord.name}</b><span>{openRecord.status} preview state · {openRecord.detail}. This record is local to the current preview session.</span></div>}</div></section>;
  }

  if (page === "domain" || page === "technical-care" || page === "system-health") {
    return <section className="workflow-surface"><div className="workflow-card"><div className="workflow-heading"><div><p>MANAGED OPERATIONS</p><h2>{page === "domain" ? "Prepare your domain launch." : page === "technical-care" ? "Technical care is available after delivery." : "Safe system health summaries."}</h2><span>{page === "domain" ? "Domain connection begins when the project is ready for launch." : "Operational details appear only for accepted managed-service customers."}</span></div><Building2 size={24} /></div><div className="ops-grid"><div><span>Current visibility</span><b>Preview mode</b></div><div><span>Managed service</span><b>Not accepted</b></div><div><span>Credentials</span><b>Never exposed</b></div></div><button className="dash-primary" onClick={() => navigate("/workspace/management")}>Request managed services</button></div></section>;
  }

  return null;
}
