import * as Icons from "lucide-react";
import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, ChevronRight, CircleCheck, ExternalLink, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { process, services } from "@/data/site";
import { PublicAccountCallout } from "@/components/PublicAccountCallout";
import { SiteShell } from "@/components/SiteShell";

const iconFor = (name: string) => Icons[name as keyof typeof Icons] as React.ComponentType<{ size?: number }>;
const appear = { hidden: { opacity: 0, y: 22 }, visible: { opacity: 1, y: 0 } };

export default function Home() {
  return <SiteShell><main>
    <section className="hero"><div className="hero-grid-glow" /><div className="hero-copy"><motion.p className="eyebrow" variants={appear} initial="hidden" animate="visible" transition={{ duration: .45 }}><Sparkles size={12} /> PROFESSIONAL WEBSITES & DIGITAL SYSTEMS</motion.p><motion.h1 variants={appear} initial="hidden" animate="visible" transition={{ duration: .55, delay: .07 }}>YOUR BUSINESS<br />DESERVES MORE<br />THAN A <strong>LINK PAGE.</strong></motion.h1><motion.p className="hero-lead" variants={appear} initial="hidden" animate="visible" transition={{ duration: .5, delay: .14 }}>We build polished websites and practical digital systems that help your business feel credible, easier to choose, and ready to grow.</motion.p><motion.div className="hero-points" variants={appear} initial="hidden" animate="visible" transition={{ duration: .5, delay: .2 }}><span><CheckCircle2 /> Preview before payment</span><span><CheckCircle2 /> Clear revision route</span><span><CheckCircle2 /> Built for your business</span></motion.div><motion.div className="hero-buttons" variants={appear} initial="hidden" animate="visible" transition={{ duration: .5, delay: .27 }}><Link href="/start-project" className="primary-button">Start your project <ArrowRight size={16} /></Link><Link href="/examples" className="secondary-button">Explore build directions <ExternalLink size={15} /></Link></motion.div><PublicAccountCallout /><div className="hero-note"><div className="avatar-stack"><i /><i /><i /></div><span><b>Private by design</b><br />Your project stays in your workspace.</span></div></div>
      <motion.div className="device-stage" initial={{ opacity: 0, scale: .96, x: 20 }} animate={{ opacity: 1, scale: 1, x: 0 }} transition={{ duration: .8, delay: .12 }}><div className="orb orb-one" /><div className="orb orb-two" /><div className="desktop-device"><div className="device-top"><span /><span /><span /><b>FERIXBUILDER</b><em>Preview</em></div><div className="screen"><div className="screen-sidebar"><b>O</b><span /><span /><span /><span /></div><div className="screen-main"><p>WORK THAT<br /><strong>MOVES YOU FORWARD.</strong></p><div className="screen-row"><i /><i /><i /></div><div className="screen-card"><b>Project preview</b><span>Refined for every screen</span><button>View work</button></div></div></div></div><div className="phone-device"><div className="phone-notch" /><p>FRESH IDEAS.<br /><strong>REAL RESULTS.</strong></p><div /><button>Let's build</button></div><div className="preview-badge"><ShieldCheck size={24} /><p><b>Review the work<br />before you pay.</b><br /><span>That’s the promise.</span></p></div></motion.div>
    </section>
    <section className="confidence-row"><p>BUILT FOR BUSINESSES THAT WANT A CLEARER DIGITAL PRESENCE</p><div><span>Clarity first</span><span>Made to convert</span><span>Responsive by default</span><span>Optional long-term care</span></div></section>
    <section className="services-section"><div className="section-intro"><div><p className="eyebrow light"><Sparkles size={12} /> WHAT WE CAN BUILD</p><h2>WEBSITES AND SYSTEMS<br />BUILT AROUND <em>YOUR BUSINESS.</em></h2></div><div><p>From a focused public website to a custom customer experience, we create useful digital work around what the business actually needs.</p><Link href="/services" className="small-link">See all services <ChevronRight size={14} /></Link></div></div><div className="service-cards">{services.map(([icon, title, text]) => { const Icon = iconFor(icon); return <motion.article key={title} whileHover={{ y: -5 }} transition={{ duration: .2 }}><Icon size={25} /><h3>{title}</h3><p>{text}</p><Link href="/services" aria-label={`Explore ${title}`}><ArrowRight size={16} /></Link></motion.article>; })}</div></section>
    <section className="process-section"><div className="process-head"><p className="eyebrow"><Sparkles size={12} /> HOW IT WORKS</p><h2>SIMPLE PROCESS. <strong>MEANINGFUL RESULTS.</strong></h2></div><div className="process-line">{process.map(([number, title, text], index) => <motion.article key={number} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .04 }}><div className={`process-icon p${index}`}><span>{number}</span></div><b>{title}</b><p>{text}</p></motion.article>)}</div></section>
    <section className="showcase-pricing"><div className="showcase-card"><p className="eyebrow light"><Sparkles size={12} /> BUILD DIRECTIONS</p><h2>WHAT YOUR<br />WORK CAN <em>BECOME.</em></h2><p className="showcase-lead">Every project is built from your requirements. Explore the kinds of experience we can shape together.</p><Link href="/examples" className="small-link">Explore directions <ChevronRight size={14} /></Link><div className="mini-shots"><div className="shot one"><span>Brand-led<br />presence</span></div><div className="shot two"><span>Commerce<br />journey</span></div><div className="shot three"><span>Service<br />system</span></div></div></div><div className="pricing-card"><p className="eyebrow light"><Sparkles size={12} /> CLEARER SCOPING</p><h2>PLANS THAT FIT<br />THE <em>WORK AHEAD.</em></h2><p>Choose a starting direction. We confirm the final scope and quote after we understand the project.</p><div className="tiers">{[["Essential", "A focused, professional start."], ["Growth", "For richer business experiences."], ["Custom", "For unique systems and products."]].map(([name, text], index) => <div className={index === 1 ? "featured" : ""} key={name}><span>{name}</span><p>{text}</p><b>{index === 1 ? "Most selected" : "Tailored quote"}</b><Link href="/pricing">Explore <ArrowRight size={13} /></Link></div>)}</div></div></section>
    <section className="bottom-cta"><div><span className="cta-spark"><Sparkles size={20} /></span><p><b>Ready to build a stronger digital presence?</b><br />Let’s start with the business and the outcome.</p></div><div><Link href="/start-project" className="primary-button">Start your project <ArrowRight size={16} /></Link><Link href="/register" className="secondary-button">Create account <CircleCheck size={15} /></Link><Link href="/dashboard" className="bottom-login">Log in</Link></div></section>
  </main></SiteShell>;
}
