import { useState, type ComponentType } from "react";
import {
  Bell, CalendarDays, Check, ChevronDown, CircleHelp, Clock3, Download, Eye, FolderKanban,
  Globe2, Headphones, LayoutDashboard, Menu, MessageCircle, PackageCheck, Plus, Search,
  Settings2, ShieldCheck, Sparkles, UserRound, WalletCards, X,
} from "lucide-react";
import { Link, useLocation } from "wouter";
import FeatureSurface from "./FeatureSurface";
import { getPreviewAccount } from "@/lib/customerAccess";

type IconType = ComponentType<{ size?: number }>;
type WorkspacePageKey = "dashboard" | "onboarding" | "project" | "files" | "preview" | "revisions" | "payments" | "downloads" | "customers" | "products" | "bookings" | "domain" | "technical-care" | "management" | "system-health" | "support" | "settings";

type NavItem = readonly [IconType, string, string];

export const dashboardSections: readonly [string, readonly NavItem[]][] = [
  ["WORKSPACE", [[LayoutDashboard, "Dashboard", "/dashboard"], [FolderKanban, "Onboarding", "/workspace/onboarding"], [FolderKanban, "My project", "/workspace/project"], [FolderKanban, "Project files", "/workspace/files"], [Eye, "Preview website", "/workspace/preview"], [MessageCircle, "Revisions", "/workspace/revisions"], [WalletCards, "Payments", "/workspace/payments"], [Download, "Downloads", "/workspace/downloads"]]],
  ["BUSINESS", [[UserRound, "Customers", "/workspace/customers"], [PackageCheck, "Products", "/workspace/products"], [CalendarDays, "Bookings", "/workspace/bookings"], [Globe2, "Domain", "/workspace/domain"]]],
  ["CARE", [[Settings2, "Technical care", "/workspace/technical-care"], [ShieldCheck, "Management request", "/workspace/management"], [ShieldCheck, "System health", "/workspace/system-health"], [Headphones, "Support", "/workspace/support"]]],
  ["ACCOUNT", [[Settings2, "Settings", "/workspace/settings"]]],
] as const;

export const dashboardMilestones = ["Brief received", "Scope confirmed", "In build", "Preview ready", "Approved", "Delivery"];
export const dashboardTasks = [["Design direction", "Complete", true], ["Frontend build", "Complete", true], ["Business copy", "In progress", false], ["Content handover", "In progress", false], ["Final quality check", "Next", false]] as const;

const pages: Record<WorkspacePageKey, { kicker: string; title: string; description: string; primary: string; metrics: [string, string, string][]; detailTitle: string; detail: string; rows: string[] }> = {
  dashboard: { kicker: "CUSTOMER WORKSPACE / PROJECT TRACKING", title: "Your project request is in progress", description: "Your account is ready and your submitted requirements are now waiting for FerixBuilder review.", primary: "Start another request", metrics: [["Account", "Created", "Email verified"], ["Requirements", "Submitted", "Project brief complete"], ["Project status", "Awaiting review", "Team review comes next"], ["Quote", "Pending", "Prepared after review"], ["Delivery", "Not started", "Preview before payment"]], detailTitle: "Your project lifecycle", detail: "Your request has been received. FerixBuilder reviews the requirements before issuing the scope, quote, build, preview, approval, payment, and delivery stages.", rows: ["Account created", "Requirements submitted", "Awaiting review", "Quote", "Development", "Preview", "Approval", "Payment", "Delivery"] },
  onboarding: { kicker: "WORKSPACE / ONBOARDING", title: "Build a complete project brief", description: "Provide the business context that makes a tailored delivery possible.", primary: "Continue onboarding", metrics: [["Stages", "5", "Business to review"], ["Draft", "Saved", "Continue later"], ["Request", "Not submitted", "Preview mode"]], detailTitle: "Structured request", detail: "The onboarding sequence captures only the information that applies to the work you need.", rows: ["Business details", "Brand direction", "Content material", "Requirements review"] },
  project: { kicker: "WORKSPACE / MY PROJECT", title: "Your project, clearly mapped", description: "Review the agreed scope, delivery route, and current project context.", primary: "View request", metrics: [["Current phase", "In build", "Layout in progress"], ["Scope", "Confirmed", "6 work areas"], ["Target", "Responsive", "Desktop + mobile"]], detailTitle: "Project brief", detail: "A polished public site and customer workspace designed around the way FerixBuilder delivers work.", rows: ["Business goals recorded", "Site structure confirmed", "Project direction active", "Review point scheduled"] },
  files: { kicker: "WORKSPACE / PROJECT FILES", title: "Secure project material", description: "Keep brand, content, and reference material private and ready for the build.", primary: "Add project file", metrics: [["Uploaded", "0", "Preview mode"], ["Storage", "Private", "Authorised only"], ["Requirements", "Open", "Provide later allowed"]], detailTitle: "Project library", detail: "Files are attached to the correct project and remain available to the delivery team.", rows: ["Brand assets", "Copy documents", "Screenshots", "Reference material"] },
  preview: { kicker: "WORKSPACE / PREVIEW WEBSITE", title: "Review your private preview", description: "Explore the current version before approval or payment.", primary: "Open preview", metrics: [["Preview", "Ready", "Private link active"], ["Screens", "12", "Responsive layouts"], ["Review route", "Open", "Feedback welcome"]], detailTitle: "Preview workspace", detail: "This is where you check the experience, share feedback, and approve the direction when it feels right.", rows: ["Desktop layout available", "Mobile layout available", "Preview link ready", "Approval route prepared"] },
  revisions: { kicker: "WORKSPACE / REVISIONS", title: "Keep refinements organised", description: "Use a clear revision route so every change has context and status.", primary: "Request changes", metrics: [["Included changes", "2", "In this delivery"], ["Open request", "0", "Nothing waiting"], ["Response route", "Ready", "Review first"]], detailTitle: "Revision board", detail: "Describe what needs to change, attach the relevant context, and follow the request through review.", rows: ["Design direction reviewed", "Copy feedback ready", "Layout changes available", "Final sign-off next"] },
  payments: { kicker: "WORKSPACE / PAYMENTS", title: "Approval before payment", description: "Your financial route stays tied to the project approval process.", primary: "View payment route", metrics: [["Project value", "Tailored", "Scope-based quote"], ["Payment status", "Not due", "After approval"], ["Invoices", "0", "Preview mode"]], detailTitle: "Payment clarity", detail: "Payment becomes available only when the reviewed work is approved. No payment is processed in preview mode.", rows: ["Scope confirmed", "Preview available", "Approval pending", "Payment route unlocks next"] },
  downloads: { kicker: "WORKSPACE / DOWNLOADS", title: "Delivery files, in one place", description: "Your released files, handover notes, and source packages will appear here.", primary: "View delivery guide", metrics: [["Delivery state", "Prepared", "After approval"], ["Files", "0", "Preview mode"], ["Storage", "Private", "Authorised access"]], detailTitle: "Release centre", detail: "Delivery files remain private until the project reaches its release point.", rows: ["Handover plan prepared", "Source package protected", "Release checkpoint pending", "Download route ready"] },
  customers: { kicker: "BUSINESS / CUSTOMERS", title: "Customer relationships, organised", description: "A focused view of customer records connected to your business delivery.", primary: "Add customer", metrics: [["Customers", "0", "Preview workspace"], ["Active", "0", "No live records"], ["Access", "Private", "Business scoped"]], detailTitle: "Customer records", detail: "Customer data will stay connected to the correct business workspace and project context.", rows: ["Contact profiles", "Project associations", "Support history", "Access controls"] },
  products: { kicker: "BUSINESS / PRODUCTS", title: "Products and offers", description: "Shape the products or service offers that your website needs to present.", primary: "Add product", metrics: [["Products", "0", "Preview workspace"], ["Collections", "0", "Not configured"], ["Availability", "Ready", "For setup"]], detailTitle: "Offer catalogue", detail: "Add your business offers here when product or service content becomes part of the project.", rows: ["Product details", "Pricing information", "Media preparation", "Website placement"] },
  bookings: { kicker: "BUSINESS / BOOKINGS", title: "Booking operations", description: "A dedicated space for availability, booking routes, and service timing.", primary: "Create booking type", metrics: [["Booking types", "0", "Preview workspace"], ["Availability", "Not set", "Setup needed"], ["Requests", "0", "No live records"]], detailTitle: "Booking flow", detail: "This route will manage the booking setup that customers see on your public experience.", rows: ["Service availability", "Booking questions", "Confirmation rules", "Customer notifications"] },
  domain: { kicker: "BUSINESS / DOMAIN", title: "Your domain and web address", description: "Keep domain information, connection status, and launch details visible.", primary: "Connect domain", metrics: [["Domain", "Not connected", "Preview workspace"], ["SSL", "Ready", "After connection"], ["Launch", "Planned", "Project route"]], detailTitle: "Domain centre", detail: "When your website is ready, this page will guide the domain connection and launch transition.", rows: ["Domain selection", "DNS connection", "SSL activation", "Launch confirmation"] },
  "technical-care": { kicker: "CARE / TECHNICAL CARE", title: "Keep the platform cared for", description: "Optional ongoing care for the site after delivery and launch.", primary: "Explore technical care", metrics: [["Care plan", "Optional", "After delivery"], ["Updates", "Ready", "Managed route"], ["Monitoring", "Available", "If enabled"]], detailTitle: "Technical care route", detail: "Technical care is an optional managed service for a site that needs continuing attention after launch.", rows: ["Update planning", "Performance checks", "Platform maintenance", "Support route"] },
  management: { kicker: "CARE / MANAGEMENT REQUEST", title: "Request managed service", description: "Tell FerixBuilder which ongoing services your project may need after delivery.", primary: "Request management", metrics: [["Request", "Not submitted", "Preview mode"], ["Review", "Required", "Before acceptance"], ["Access", "Safe summaries", "After acceptance"]], detailTitle: "Management application", detail: "Management requests are reviewed by FerixBuilder before any hosting or support agreement begins.", rows: ["Select services", "Share requirements", "Team review", "Agreement response"] },
  "system-health": { kicker: "CARE / SYSTEM HEALTH", title: "System visibility and health", description: "A focused area for platform status, checks, and operational reassurance.", primary: "Run health check", metrics: [["Platform status", "Healthy", "Preview value"], ["Monitoring", "Ready", "If enabled"], ["Backups", "Planned", "Managed care"]], detailTitle: "Health overview", detail: "This route will surface operational checks once technical care is active for a live project.", rows: ["Platform status", "Performance checks", "Backup readiness", "Operational activity"] },
  support: { kicker: "CARE / SUPPORT", title: "Get the project help you need", description: "Open a support conversation with the correct project context already attached.", primary: "Open support ticket", metrics: [["Open tickets", "0", "Preview workspace"], ["Response route", "Ready", "Project context"], ["Project team", "Available", "When active"]], detailTitle: "Support workspace", detail: "Support requests keep the conversation attached to your project delivery route instead of scattered messages.", rows: ["Open a request", "Share context", "Track the reply", "Keep delivery moving"] },
  settings: { kicker: "ACCOUNT / SETTINGS", title: "Control your workspace preferences", description: "Manage your profile and which project notifications you receive.", primary: "Save settings", metrics: [["Profile", "Ready", "Preview account"], ["Members", "1", "Business owner"], ["Notifications", "Configured", "Local preview"]], detailTitle: "Workspace settings", detail: "Keep account and business preferences organised without exposing operational platform controls.", rows: ["Profile details", "Business members", "Notifications", "Account preferences"] },
};

const mobileLinks: readonly [IconType, string, string][] = [[LayoutDashboard, "Home", "/dashboard"], [FolderKanban, "Project", "/workspace/project"], [Eye, "Preview", "/workspace/preview"], [CircleHelp, "Support", "/workspace/support"]];

export default function WorkspacePage({ page }: { page: WorkspacePageKey }) {
  const [location, navigate] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const account = getPreviewAccount();
  const accountName = account?.fullName || "FerixBuilder customer";
  const info = pages[page];
  const notify = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(null), 2600); };
  const primaryTargets: Partial<Record<WorkspacePageKey, string>> = { dashboard: "/workspace/onboarding", project: "/workspace/files", domain: "/workspace/management", "technical-care": "/workspace/management", "system-health": "/workspace/management", support: "/workspace/support" };
  const activatePrimary = () => {
    const target = primaryTargets[page];
    if (target && target !== location) return navigate(target);
    document.getElementById("customer-workflow")?.scrollIntoView({ behavior: "smooth", block: "start" });
  };
  const iconFor = (index: number) => [FolderKanban, MessageCircle, Eye, WalletCards, Download][index % 5];
  return <div className="dashboard-shell workspace-shell">
    <button aria-label="Close workspace menu" className={mobileOpen ? "drawer-backdrop open" : "drawer-backdrop"} onClick={() => setMobileOpen(false)} />
    <aside className={mobileOpen ? "dash-sidebar mobile-open" : "dash-sidebar"}><div className="dash-brand"><span><Sparkles size={15} /></span><b>Ferix</b>Builder<button onClick={() => setMobileOpen(false)}><X size={18} /></button></div><div className="drawer-caption">Every customer-workspace page is available here.</div>{dashboardSections.map(([title, items]) => <div className="dash-nav-group" key={title}><p>{title}</p>{items.map(([Icon, label, href]) => <Link key={href} href={href} className={location === href ? "active" : ""} onClick={() => setMobileOpen(false)}><Icon size={16} /><span>{label}</span>{label === "Revisions" && <b>2</b>}</Link>)}</div>)}<div className="dash-profile"><div className="profile-avatar">{accountName.slice(0, 2).toUpperCase()}</div><div><b>{accountName}</b><span>Preview account</span></div><ChevronDown size={14} /></div></aside>
    <main className="dash-main"><header className="dash-header"><button className="dash-menu" onClick={() => setMobileOpen(true)}><Menu size={20} /></button><div className="dash-search"><Search size={17} /><input placeholder="Search your workspace..." /><kbd>⌘ K</kbd></div><div className="dash-header-actions"><button aria-label="Open project updates" onClick={() => navigate("/workspace/project")}><Bell size={18} /><i>2</i></button><button aria-label="Open support messages" onClick={() => navigate("/workspace/support")}><MessageCircle size={18} /><i>1</i></button><Link href="/" className="dash-return">Back to site</Link></div></header>
      <section className="workspace-hero"><div><p className="dash-kicker">{info.kicker}</p><h1>{info.title}</h1><p>{info.description}</p></div><button className="dash-primary" onClick={activatePrimary}><Plus size={17} /> {info.primary}</button></section>
      <section className="workspace-metrics">{info.metrics.map(([label, value, note], index) => { const Icon = iconFor(index); return <article className="dash-stat" key={label}><span className={`stat-icon ${["purple", "mint", "blue", "orange", "violet"][index % 5]}`}><Icon /></span><div><p>{label}</p><h2>{value}</h2><small>{note}</small></div></article>; })}</section>
      {["onboarding", "project", "files", "preview", "revisions", "payments", "downloads", "customers", "products", "bookings", "domain", "technical-care", "management", "system-health", "support", "settings"].includes(page) ? <div id="customer-workflow"><FeatureSurface page={page} notify={notify} navigate={navigate} /></div> : <section className="workspace-content"><article className="dash-card workspace-feature"><div className="card-title"><div><span className="icon-box purple"><FolderKanban size={18} /></span><div><h2>{info.detailTitle}</h2><p>Dedicated FerixBuilder customer-workspace page</p></div></div><button onClick={() => navigate("/workspace/project")}>View project</button></div><p className="workspace-copy">{info.detail}</p><div className="workspace-route">{info.rows.map((row, index) => <div key={row}><i>{index < 2 ? <Check size={13} /> : index + 1}</i><span>{row}</span></div>)}</div></article><aside className="workspace-side"><article className="dash-card"><div className="card-title"><div><span className="icon-box blue"><Clock3 size={18} /></span><div><h2>What happens next</h2><p>Keep your delivery route moving.</p></div></div></div><ol>{info.rows.slice(0, 3).map((row, index) => <li key={row}><b>0{index + 1}</b><span>{row}</span></li>)}</ol><button className="review-button" onClick={() => navigate("/workspace/preview")}>Continue in preview</button></article><article className="dash-card workspace-activity"><div className="card-title"><div><span className="icon-box purple"><Bell size={18} /></span><div><h2>Workspace activity</h2><p>Latest project signals.</p></div></div></div><p><b>Workspace ready</b><br />This dedicated page is available from desktop and mobile navigation.</p><p><b>Preview mode active</b><br />No account or payment lock is applied.</p></article></aside></section>}
      <section className="workspace-support"><article className="dash-card"><CircleHelp size={22} /><div><h2>Need help with this area?</h2><p>Support stays connected to this customer workspace.</p></div><Link href="/workspace/support" className="dash-primary small">Open support</Link></article><article className="dash-card"><Headphones size={22} /><div><h2>Project team</h2><p>FerixBuilder is ready to guide the next delivery step.</p></div><button onClick={() => navigate("/workspace/support")}>Message team</button></article></section>
    </main><nav className="dash-bottom-nav" aria-label="Mobile dashboard navigation">{mobileLinks.map(([Icon, label, href]) => <Link key={href} href={href} className={location === href ? "active" : ""}><Icon size={18} /><span>{label}</span></Link>)}<button onClick={() => setMobileOpen(true)}><Menu size={18} /><span>Workspace</span></button></nav>{notice && <div className="dash-notice"><Check size={15} /> {notice}</div>}</div>;
}
