import { httpBatchLink } from "@trpc/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";
import superjson from "superjson";
import { Route, Switch } from "wouter";
import AuthPage from "@/pages/AuthPage";
import Contact from "@/pages/Contact";
import Dashboard from "@/pages/Dashboard";
import DetailPage from "@/pages/DetailPage";
import Home from "@/pages/Home";
import StartProject from "@/pages/StartProject";
import WorkspacePage from "@/pages/WorkspacePage";
import { trpc } from "@/lib/trpc";

function Router() { const workspacePage = (page: Parameters<typeof WorkspacePage>[0]["page"]) => <WorkspacePage page={page} />; return <Switch><Route path="/" component={Home} /><Route path="/services">{() => <DetailPage page="services" />}</Route><Route path="/how-it-works">{() => <DetailPage page="how" />}</Route><Route path="/examples">{() => <DetailPage page="examples" />}</Route><Route path="/pricing">{() => <DetailPage page="pricing" />}</Route><Route path="/about">{() => <DetailPage page="about" />}</Route><Route path="/faq">{() => <DetailPage page="faq" />}</Route><Route path="/contact" component={Contact} /><Route path="/start-project" component={StartProject} /><Route path="/dashboard" component={Dashboard} /><Route path="/workspace/onboarding">{() => workspacePage("onboarding")}</Route><Route path="/workspace/project">{() => workspacePage("project")}</Route><Route path="/workspace/files">{() => workspacePage("files")}</Route><Route path="/workspace/preview">{() => workspacePage("preview")}</Route><Route path="/workspace/revisions">{() => workspacePage("revisions")}</Route><Route path="/workspace/payments">{() => workspacePage("payments")}</Route><Route path="/workspace/downloads">{() => workspacePage("downloads")}</Route><Route path="/workspace/customers">{() => workspacePage("customers")}</Route><Route path="/workspace/products">{() => workspacePage("products")}</Route><Route path="/workspace/bookings">{() => workspacePage("bookings")}</Route><Route path="/workspace/domain">{() => workspacePage("domain")}</Route><Route path="/workspace/technical-care">{() => workspacePage("technical-care")}</Route><Route path="/workspace/management">{() => workspacePage("management")}</Route><Route path="/workspace/system-health">{() => workspacePage("system-health")}</Route><Route path="/workspace/support">{() => workspacePage("support")}</Route><Route path="/workspace/settings">{() => workspacePage("settings")}</Route><Route path="/login">{() => <AuthPage mode="login" />}</Route><Route path="/register">{() => <AuthPage mode="register" />}</Route><Route path="/verify-email">{() => <AuthPage mode="verify" />}</Route><Route path="/forgot-password">{() => <AuthPage mode="forgot" />}</Route><Route path="/reset-password">{() => <AuthPage mode="reset" />}</Route><Route component={Home} /></Switch>; }
export default function App() { const [queryClient] = useState(() => new QueryClient()); const [client] = useState(() => trpc.createClient({ links: [httpBatchLink({ url: "/api/trpc", transformer: superjson })] })); return <trpc.Provider client={client} queryClient={queryClient}><QueryClientProvider client={queryClient}><Router /></QueryClientProvider></trpc.Provider>; }
