import { httpBatchLink } from "@trpc/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";
import superjson from "superjson";
import { Route, Switch } from "wouter";
import AuthPage from "@/pages/AuthPage";
import Contact from "@/pages/Contact";
import Dashboard from "@/pages/Dashboard";
import DetailPage from "@/pages/DetailPage";
import Home from "@/pages/Home";
import WorkspacePage from "@/pages/WorkspacePage";
import CustomerRoute from "@/pages/CustomerRoute";
import { trpc } from "@/lib/trpc";

function Router() { const protectedPage = (page: Parameters<typeof WorkspacePage>[0]["page"]) => <CustomerRoute><WorkspacePage page={page} /></CustomerRoute>; return <Switch><Route path="/" component={Home} /><Route path="/services">{() => <DetailPage page="services" />}</Route><Route path="/how-it-works">{() => <DetailPage page="how" />}</Route><Route path="/examples">{() => <DetailPage page="examples" />}</Route><Route path="/pricing">{() => <DetailPage page="pricing" />}</Route><Route path="/about">{() => <DetailPage page="about" />}</Route><Route path="/faq">{() => <DetailPage page="faq" />}</Route><Route path="/contact" component={Contact} /><Route path="/dashboard">{() => <CustomerRoute><Dashboard /></CustomerRoute>}</Route><Route path="/workspace/onboarding">{() => <CustomerRoute allowIncomplete><WorkspacePage page="onboarding" /></CustomerRoute>}</Route><Route path="/workspace/project">{() => protectedPage("project")}</Route><Route path="/workspace/files">{() => protectedPage("files")}</Route><Route path="/workspace/preview">{() => protectedPage("preview")}</Route><Route path="/workspace/revisions">{() => protectedPage("revisions")}</Route><Route path="/workspace/payments">{() => protectedPage("payments")}</Route><Route path="/workspace/downloads">{() => protectedPage("downloads")}</Route><Route path="/workspace/customers">{() => protectedPage("customers")}</Route><Route path="/workspace/products">{() => protectedPage("products")}</Route><Route path="/workspace/bookings">{() => protectedPage("bookings")}</Route><Route path="/workspace/domain">{() => protectedPage("domain")}</Route><Route path="/workspace/technical-care">{() => protectedPage("technical-care")}</Route><Route path="/workspace/management">{() => protectedPage("management")}</Route><Route path="/workspace/system-health">{() => protectedPage("system-health")}</Route><Route path="/workspace/support">{() => protectedPage("support")}</Route><Route path="/workspace/settings">{() => protectedPage("settings")}</Route><Route path="/login">{() => <AuthPage mode="login" />}</Route><Route path="/register">{() => <AuthPage mode="register" />}</Route><Route path="/verify-email">{() => <AuthPage mode="verify" />}</Route><Route path="/forgot-password">{() => <AuthPage mode="forgot" />}</Route><Route path="/reset-password">{() => <AuthPage mode="reset" />}</Route><Route component={Home} /></Switch>; }
export default function App() { const [queryClient] = useState(() => new QueryClient()); const [client] = useState(() => trpc.createClient({ links: [httpBatchLink({ url: "/api/trpc", transformer: superjson })] })); return <trpc.Provider client={client} queryClient={queryClient}><QueryClientProvider client={queryClient}><Router /></QueryClientProvider></trpc.Provider>; }
