import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
import "./responsive.css";
import "./auth-cta.css";
import "./account-flow.css";
import "./dashboard.css";
import "./dashboard-mobile.css";
import "./workspace.css";
import "./workflow.css";
import "./workflow-fixes.css";
import "./project-workflow.css";
import "./onboarding-flow.css";
createRoot(document.getElementById("root")!).render(<App />);
