import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
import "./responsive.css";
import "./auth-cta.css";
import "./account-flow.css";
import "./dashboard.css";
import "./dashboard-mobile.css";
import "./workspace.css";
import "./workflow.css";
import "./workflow-fixes.css";
import "./project-workflow.css";
import "./onboarding-flow.css";
import "./dashboard-hubs.css";
import "./dashboard-reference.css";
import "./dashboard-account-manager.css";
import "./dashboard-lifecycle-feedback.css";
import "./dashboard-journey-context.css";
import "./dashboard-cockpits.css";
import "./workflow-balance.css";
import "./workflow-card-alignment.css";
createRoot(document.getElementById("root")!).render(<App />);
